data_config:
  cand_pool_dir_name: passage/
  enable_query_instruct: true
  image_size: 224, 224
  query_instruct_path: instructions/query_instructions.tsv
  shuffle_cand: true
  test_dir_name: query/val
  train_dir_name: query/train
  val_dir_name: query/val
dataloader_config:
  batch_size: 2048
  num_workers: 5
dist_config:
  dist_url: env://
embed_config:
  cand_pools_config:
    cand_pools_name_to_embed:
    - arxiv12_val
    embed_union_pool: true
    enable_embed: true
  embed_dir_name: embed
  test_datasets_config:
    correspond_cand_pools_name:
    - arxiv12_val
    datasets_name:
    - arxiv12
    enable_embed: false
  train_datasets_config:
    correspond_cand_pools_name: null
    datasets_name: null
    enable_embed: false
  use_fp16: true
  val_datasets_config:
    correspond_cand_pools_name:
    - arxiv12_val
    datasets_name:
    - arxiv12
    enable_embed: true
experiment:
  description: ${model.name} ${model.size} ${experiment.instruct_status} ${experiment.exp_name}
  exp_name: InBatch
  instruct_status: Instruct
  path_suffix: ${model.short_name}/${model.size}/${experiment.instruct_status}/${experiment.exp_name}/
model:
  ckpt_config:
    ckpt_dir: /root/uniir/checkpoint/CLIP_SF/Large/Instruct/ArxivQA12/
    ckpt_name: clip_sf_epoch_19.pth
  clip_vision_model_name: ViT-L/14
  name: CLIPScoreFusion
  pretrained_clip_model_dir: checkpoint/CLIP/
  short_name: CLIP_SF
  size: Large
seed: 2023
